### ISSUE TITLE
Background scenarios cause an error

### ISSUE THREAD

**Issue by s-burtonshaw** [znevrly/cucumber-junit-convert#5]
Background steps in feature will cause an error e.g.,

    Feature: Feature with background steps
        Background:
            Given some precondition
            And some other precondition

        Scenario: Scenario 1
            When I do something
            Then some result

will cause an error when converting like: 

    [16:57:09] Error: Missing attribute value. attribute: {classname}, parent: <testcase>
        at new XMLAttribute (\node_modules\xmlbuilder\lib\XMLAttribute.js:14:15)
        at XMLElement.module.exports.XMLElement.attribute (\node_modules\xmlbuilder\lib\XMLElement.js:72:35)
        at XMLElement.module.exports.XMLElement.attribute (\node_modules\xmlbuilder\lib\XMLElement.js:65:16)
        at new XMLElement (\node_modules\xmlbuilder\lib\XMLElement.js:24:14)
        at XMLElement.module.exports.XMLNode.node (\node_modules\xmlbuilder\lib\XMLNode.js:163:15)
        at XMLElement.module.exports.XMLNode.element (\node_modules\xmlbuilder\lib\XMLNode.js:110:28)
        at XMLElement.module.exports.XMLNode.ele (\node_modules\xmlbuilder\lib\XMLNode.js:392:19)
        at TestCase.build (\node_modules\junit-report-builder\src\test_case.js:94:39)
        at \node_modules\junit-report-builder\src\test_suite.js:82:14
        at arrayEach (\node_modules\lodash\lodash.js:530:11)

  The solution is to just skip elements of type="background"

**Comment by s-burtonshaw** [comment]
@znevrly Thanks for merging this PR. Will you be publishing a new version to NPM anytime soon? 

Ps. will need a changelog update if you do (I missed it in this PR)

**Comment by znevrly** [comment]
Released 1.1.1. Thanks for fix.

**Comment by znevrly** [comment]
Released.
